services:
  web:
    build: .

    ports:
      - "5000:5000"

    volumes:
      - .:/app

    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/cinema_db

    depends_on:
      - db

  db:
    image: postgres:16

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cinema_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: